$:.unshift('lib')
require 'rubygems'
require 'rake/gempackagetask'
require 'fileutils'
require 'ftools'
require 'rake/testtask'
include FileUtils

#NAME = "sorts"
#VERS = JRLBM::VERSION
#PKG = "#{NAME}-#{VERS}"
#JARS = Dir.glob("vendor/*.jar")
#PKG_FILES = JARS + Dir.glob("lib/**/*.rb") << "changelog"

=begin
SPEC = Gem::Specification.new do |s|
  s.name = NAME
  s.version = VERS
  s.platform = Gem::Platform::CURRENT
  s.summary = "JRuby wrapper for LBM."
  s.description = s.summary
  s.author = "greeves"
  s.has_rdoc = true
  s.email = "greeves@drwholdings.com"
  s.files = PKG_FILES
  s.executables = "jrlbm-info", "jrlbm-proxy"
  s.add_development_dependency('mocha')
end
=end

task :default => :test

Rake::TestTask.new do |t|
  t.libs << "test/unit"
  t.test_files = FileList['test/test_*.rb']
end

=begin
Rake::GemPackageTask.new(SPEC) do |pkg|
  pkg.need_zip = false
  pkg.need_tar = false
end

desc "Package and install the gem."
task :p => [:gem] do 
  puts "Installing jrlbm gem..."
  %x[jgem install -V pkg/*.gem]
end

desc "Upload as a gem to the DRW internal RubyGems server."
task :upload => [:package] do
	%x[scp pkg/*.gem buildadmin@sup-chiant01:/data/rubygems/gems/]
end

desc "Clean project files."
task :clean do
  rm_rf 'pkg'
end

desc "Update the change log."
task :change_log do 
  %x[git log --pretty=short --grep=release > changelog]
  %x[git commit changelog --amend --reuse-message HEAD]
endi
=end
